{
  "id": {{{uuid}}},
  "requestedBy": {{{userName}}},
  "requestedOn": {{{moment}}},
  "serviceName": {{{service.serviceName}}},
  "serviceId": {{{service.serviceId}}},
  "workflow": {{{service.workflow}}},
  "currentActivity": null,
  "completedActivities": [
  ]
}
