---
client:
  ui:
    actionButtonTooltip: "Click this button to run the operation on the selected targets"
    actionButtonValue: "Perform Operation on Selected Targets"
    advancedMode: false
    beforeDataMessage: "Click the Find Targets Button"
    confirmButtonTooltip: "Click here to performing the operation"
    confirmButtonValue: "Confirm Operation on Selected Targets"
    confirmDialogTitle: "The Following Operations Will Be Performed"
    doneButtonTooltip: "Click here to close this window"
    doneButtonValue: Done
    filter:
      filterContextVariable: userName
      filterDisabled: true
      filterLabel: Username
      filterMinimumLength: 0
      filterPlaceholder: ""
      filterSecret: "%%%"
    filterButtonTooltip: "Click this button to find targets"
    filterButtonValue: "Find Target"
    filterTooltip: "Enter the Target Name"
    menuLabel: "Choose An Operation:"
    noDataMessage: "No targets were found"
    resultsDialogTitle: "The Following Operations Will Be Performed"
columns:
  -
    displayName: "Target Name"
    enableCellEdit: false
    name: Name
  -
    displayName: "Target User"
    enableCellEdit: false
    expression: $context.Name
    name: userName
  -
    displayName: Operation
    enableCellEdit: false
    name: Operation
  -
    displayName: Message
    enableCellEdit: false
    name: Message
    views:
      - results
  -
    cellTemplate: "<input class=\"ui-grid-cell-contents\" type=\"checkbox\" ng-model=\"row.entity.Selected\" ng-click=\"grid.appScope.selectionClicked(row)\" checked >"
    displayName: Selected
    enableCellEdit: true
    inputType: checkbox
    name: Selected
    type: boolean
    views:
      - choose
server:
  action:
    command: "$__l | % { Add-Member -InputObject $_ -MemberType NoteProperty -Name 'Message' -Value \"Said $($_.Operation)\" -PassThru }"
  approve: {}
  config:
    command: "@(@{'name'='One';'displayName'='Hello';'command'='Hello $userName'},@{'name'='Two';'displayName'='Goodbye'})"
    vars:
      Username: $context.userName
  confirm: {}
  connect:
    command: ~
    vars: {}
  deploy:
    worker:
      ? "Quest Active Roles"
      :
        - "msiexec /i /q W2K12-KB3134759-x64.msu"
        - "Add-PSSnapin Quest.ActiveRoles.ADManagement"
  discovery:
    command: "$ldapfilter = \"(&(anr=$filter)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))\";get-aduser -LDAPFilter $ldapfilter -Properties DistinguishedName,EmailAddress,GivenName,Surname,DisplayName,Enabled -ErrorAction Stop"
    vars:
      filter: $context.filter
serviceDisplayName: "Sample WinRM Service"
serviceId: 85BF8DEB-F904-4877-8A2E-F701222B1945
serviceName: sample-winrm-service
test: {}
